apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bitcoin-parser-worker
spec:
  replicas: 37
  template:
    metadata:
      labels:
        app: bitcoin-parser
        role: worker
        tier: middle
    spec:
      containers:
      - name: worker
        image: gcr.io/bitcoin-graph-212514/bitcoin-worker:v13
        imagePullPolicy: Always
        resources:
          limits:
            memory: "10G"
            cpu: "1.5"
          requests:
            memory: "10G"
            cpu: "1.5"      
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/shared/bitcoin-graph-108593a03cbe.json"        
        volumeMounts:
        - name: shared
          mountPath: "/etc/shared"       
      volumes:
      - name: shared
        secret:
          secretName: storage-key-file
          defaultMode: 256